<?php

namespace AppBundle\Repository;


use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
/**
 * ProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoRepository extends EntityRepository
{
    public function loadProyectoByNombre($nombre)
    {
        $q = $this
            ->createQueryBuilder('p')
            ->where('p.nombre = :nombre')
            ->setParameter('nombre', $nombre)
            ->getQuery()
        ;

        try {
            // The Query::getSingleResult() method throws an exception
            // if there is no record matching the criteria.
            $user = $q->getSingleResult();
        } catch (NoResultException $e) {
            $message = sprintf(
                'Unable to find an active admin AcmeUserBundle:User object identified by "%s".',
                $nombre
            );
            throw new UsernameNotFoundException($message, null, 0, $e);
        }

        return $user;
    }

}
