<?php

namespace AppBundle\Repository;

/**
 * ProyectoTrabajadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoTrabajadorRepository extends \Doctrine\ORM\EntityRepository
{


}
