<?php

namespace AppBundle\Repository;

/**
 * RepresentanteLegalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentanteLegalRepository extends \Doctrine\ORM\EntityRepository
{
}
