<?php

namespace AppBundle\Repository;

/**
 * TrabajadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabajadorRepository extends \Doctrine\ORM\EntityRepository
{
}
