# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    access_denied_url:    /

    providers:
        our_db_provider:
                    entity: { class: AppBundle:Persona }
    firewalls:
        dev:
                    pattern: ^/(_(profiler|wdt)|css|images|js)/
                    security: false
        main:
            pattern: ^/
            anonymous: ~
            http_basic: ~
            provider: our_db_provider
            form_login:

                login_path: /login
                check_path: /login

                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path:            /welcomepage
                target_path_parameter:          login_success
                use_referer:                    false

                # login failure redirecting options (read further below)
                failure_forward: false
                failure_path_parameter: login_fail

                # by default, the login form *must* be a POST, not a GET
                post_only:      true
                remember_me:    false

                require_previous_session: false
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
     #   - { path: ^/, roles: ROLE_USER}
     #   - { path: ^/, roles: ROLE_ADMIN}

    encoders:
      AppBundle\Entity\Persona: bcrypt
